#!/bin/bash

#set -o xtrace

# Create PHP .deb packages

FBOLD=`tput bold`
FNORM=`tput sgr0`
CLRED=`tput setaf 1`
CLGREEN=`tput setaf 2`
CLYELLOW=`tput setaf 3`
CLNC=`tput sgr0`
TXHLT="${FBOLD}${CLYELLOW}"
TXNORM="${CLNC}${FNORM}"

echo "${TXHLT}Create .deb packages for compiled PHPs${TXNORM}"
echo "    To see checkinstall's logfile interactively, use command: '$ tail -F /tmp/checkinstall.log'"

mkdir -p /vagrant/files/deb/old/

# Force rebuilding all packages
#mv /vagrant/files/deb/*.deb /vagrant/files/deb/old/ 2>/dev/null

rm -rf $HOME/.phpbrew/build/tmp.*
PHP_BUILD_FOLDERS=$HOME/.phpbrew/build/*

for PHP_BUILD in $PHP_BUILD_FOLDERS
do
  if [[ -f "$PHP_BUILD/sapi/cli/php" && -f "$PHP_BUILD/sapi/cgi/php-cgi" ]]; then

    echo "Found build files in $PHP_BUILD"

    chmod a+x "$PHP_BUILD/scripts/php-config"

  	PHP_VERSION=`$PHP_BUILD/scripts/php-config --version`
    a=( ${PHP_VERSION//./ } ) # replace points, split into array
    ((a[2]++)) # increment revision (or other part)
    PHP_VERSION_MAJOR="${a[0]}.${a[1]}" # shorten version
    PHP_VERSION_MAJOR2="${a[0]}" # 1st version digit
    PHP_INST="/opt/php/$PHP_VERSION_MAJOR"
    
    if [[ -f "$PHP_INST/bin/php" && -f "$PHP_INST/bin/php-cgi" ]]; then

      if [ -f /vagrant/files/deb/php-${PHP_VERSION}*.deb ]; then
        echo "PHP ${PHP_VERSION} .deb file is present in /vagrant/files/deb/, skip";
        continue
      fi;

      echo "Create PHP $PHP_VERSION .deb package"
  
      cd $HOME/.phpbrew/build/$PHP_VERSION_MAJOR/

      # Include in package all PHP directory contents, not only those generated by 'make install'
      find $PHP_INST/ > pkg-include-list.txt
      #find $PHP_INST/ -name *.ini -o -name *.so > pkg-include-list.txt
  
      if [ ! -f /usr/lib/apache2/modules/libphp${PHP_VERSION}.so ]; then
        echo "ERROR: Apache module libphp${PHP_VERSION}.so not found in place"
        exit 1
      fi

      if [[ "$PHP_VERSION_MAJOR" == "5.2" || "$PHP_VERSION_MAJOR" == "5.3" ]]; then
        # Force include apache module files in package, as for PHP <=5.3 it is compiled earlier by separate make call, so isn't included automatically
        echo "/usr/lib/apache2/modules/libphp${PHP_VERSION}.so" >>pkg-include-list.txt
#        echo "/etc/apache2/mods-available/php${PHP_VERSION_MAJOR2}.load" >>pkg-include-list.txt
      fi
  
      #DEPS="libmhash2,libcurl3,libmysqlclient20,apache2-bin,libapparmor1,libaspell15,libbz2-1.0,libc6,libc-client2007e,libedit2,libgcc1,libgd3,libgmp10,libicu55,libldap-2.4-2,libmagic1,libmcrypt4,libodbc1,libpcre3,libpq5,librecode0,libsnmp30,libsqlite3-0,libssl1.0.0,libstdc++6,libsybdb5,libsystemd0,libtidy-0.99-0,libxml2,libxmlrpc-epi0,libxpm4,libxslt1.1,libzip4,lsb-base,mime-support,php7.0-cli,php7.0-common,php7.0-json,php7.0-opcache,php7.0-readline,php-common,tzdata,ucf,zlib1g"
      DEPS="libmhash2,libcurl3,libmysqlclient20,apache2-bin,libapparmor1,libaspell15,libbz2-1.0,libc6,libc-client2007e,libedit2,libgcc1,libgd3,libgmp10,libicu55,libldap-2.4-2,libmagic1,libmcrypt4,libodbc1,libpcre3,libpq5,librecode0,libsnmp30,libsqlite3-0,libssl1.0.0,libstdc++6,libsybdb5,libsystemd0,libtidy-0.99-0,libxml2,libxmlrpc-epi0,libxpm4,libxslt1.1,libzip4,lsb-base,mime-support,tzdata,ucf,zlib1g"
  
      # TODO: check dependencies list
      # TODO: separated dependencies lists for PHP5/7
      # TODO: (?) include in package /etc/apache2/mods-available/php<version>.load files, avoiding name conflicts
      pkgversion=$(date '+%Y%m%d.%H%M%S')
#echo "START PACKAGING";
#continue
      #echo "Start packaging"
      checkinstall -D \
          --default \
          --install=no \
          --strip=no \
          --stripso=no \
          --fstrans=yes \
          --addso \
          --reset-uids \
          --nodoc \
          --arch=amd64 \
          --requires=$DEPS \
          --pkgname php-${PHP_VERSION} \
          --pkgversion $pkgversion \
          --pakdir /vagrant/files/deb \
          --exclude=/etc/apache2/mods-available,/etc/apache2/mods-enabled,/var/lib/apache2/module \
          --include=pkg-include-list.txt \
        >/tmp/checkinstall.log 2>&1
#          --exclude=/etc/apache2/mods-available/php5.load,/etc/apache2/mods-available/php5.load.bak~,/etc/apache2/mods-enabled/php5.load,/etc/apache2/mods-available/php7.load,/etc/apache2/mods-available/php7.load.bak~,/etc/apache2/mods-enabled/php7.load, \

    else
      echo "Not installed, skip"
    fi

  else
    echo "No build files in $PHP_BUILD"
  fi

done
