#!/bin/bash

# TODO: Delete vhost configs if their documen root not exists. But preserve user custom configs created by hand. Impossible?

source /vagrant/scripts/setvars.sh

#VHOSTS_BASEDIR=/vagrant/vhosts
VHOSTS_BASEDIR=/vhosts

if [[ -d /etc/apache2/sites-available && -d "$VHOSTS_BASEDIR" ]]; then

  #echo "${TXHLT}Configure virtual hosts${TXNORM}"

  # Loop through vhost subfolders to find new vhosts to add

  VH_FOLDERS=$VHOSTS_BASEDIR/*
  VH_CHANGED=false

  for VH_FOLDER in $VH_FOLDERS
  do
    if [ -d $VH_FOLDER ]; then
      VH_NAME=$(basename $VH_FOLDER)
      if [ ! -f /etc/apache2/sites-available/$VH_NAME.conf ]; then
        cp /vagrant/files/configs/vhost.conf /etc/apache2/sites-available/$VH_NAME.conf
        sed -i "s|%VHOST_NAME%|$VH_NAME|g" /etc/apache2/sites-available/$VH_NAME.conf
        sed -i "s|%VHOST_DOCUMENT_ROOT%|$VH_FOLDER/public_html|g" /etc/apache2/sites-available/$VH_NAME.conf
        a2ensite $VH_NAME >/dev/null
        if [ ! -d $VH_FOLDER/public_html ]; then
          mkdir $VH_FOLDER/public_html
        fi
        if [ ! -f $VH_FOLDER/.htaccess ]; then
          echo "# This file was automatically generated by provisioner 'vhosts'" >>$VH_FOLDER/.htaccess
          echo "# Uncomment one of SetHandler directives to use custom PHP version for this virtual domain" >>$VH_FOLDER/.htaccess
          echo "<FilesMatch \"\\.ph(p[2-6]?|tml)$\">" >>$VH_FOLDER/.htaccess
          # Get list of available PHP CGI handlers
          PHP_CONFS=/etc/apache2/conf-available/php*.*-cgi.conf
          for PHP_CONF in $PHP_CONFS
          do
            PHP_VER=$(echo $PHP_CONF | sed 's/.*php\([0-9\.]*\).*/\1/')
            echo "  #SetHandler application/x-httpd-php$PHP_VER" >>$VH_FOLDER/.htaccess
          done
          echo "</FilesMatch>" >>$VH_FOLDER/.htaccess
        fi
        VH_CHANGED=true
        VH_FOLDER_REL=$(echo $VH_FOLDER | sed 's|^/vagrant/||')
        echo "Added new virtual host configuration '$VH_NAME' for $VH_FOLDER_REL"
        echo "    Put your www files into $VH_FOLDER_REL/public_html"
        echo "    Switch PHP version in $VH_FOLDER_REL/.htaccess"
        echo "    or in $VH_FOLDER_REL/public_html/.htaccess (not recommended)"
      fi
    fi
  done

  if $VH_CHANGED; then
    echo "Reload Apache"
    service apache2 reload
  fi

fi